### PR TITLE
Add bypass for filedm.com

### PR DESCRIPTION
**Pull request by jaxp2**
<details> <summary>NOTICE</summary>
I dedicate any and all copyright interest in this software to the
public domain. I make this dedication for the benefit of the public at
large and to the detriment of my heirs and successors. I intend this
dedication to be an overt act of relinquishment in perpetuity of all
present and future rights to this software under copyright law.
</details>

Fixes: Adds filedm.com bypass

- [x] I made sure there are no unnecessary changes in the code*
- [x] Tested on Chromium- Browser OS
- [ ] Tested on Firefox

\* indicates required

### CODE REVIEW

**Comment by jaxp2** [comment]
ok no problem.

**Comment by jaxp2** [comment]
i personally enjoy coding 1 liners but its kinda unreadable

**Comment by reashetyrr** [comment]
on own projects they are fine, but when working with multiple people its better to make it readable >.<

**Comment by jaxp2** [comment]
better?

**Comment by jaxp2** [comment]
https://filedm.com/WJAbR

**Review by reashetyrr — APPROVED** [review]
seems to be working! :)

**Pull request merged**
