### PR TITLE
Update options.html

### PR DESCRIPTION
**Pull request by AliahX**
Just fixing the capitalization in the Faq url.

[https://discord.com/channels/876622516607656006/889075659970842634/895770412334604308](https://discord.com/channels/876622516607656006/889075659970842634/895770412334604308)

### CODE REVIEW

**Comment by idermoutia** [comment]
No need to fix it anymore, thanks.

https://github.com/FastForwardTeam/Website/pull/12/

**Comment by NotAProton** [comment]
Ref FastForwardTeam/Website#13

**Comment by AliahX** [comment]
Umm, no it still is a thing, and it needs to be fixed

**Comment by AliahX** [comment]
Don't merge this. Just merge NotAProtons request

**Pull request closed without merging**
